aviata_prototype/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('search.urls', namespace='search')),
]

search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^ajax/get_cities/$', views.get_cities, name='get_cities'),
    url(r'^ajax/check_cities/', views.check_cities, name='check_cities'),
    url(r'^results/', views.search, name='results'),
    url(r'^booking/(?P<flight_id>[0-9]+)/$', views.booking, name='booking'),
]

search/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone



# Create your models here.

class Airport(models.Model):
	airport_city = models.CharField(default="city", max_length=200)
	airport_name = models.CharField(max_length=200)
	airport_code = models.CharField(max_length=200)

	@classmethod
	def create(cls, airport_city, airport_name, airport_code):
		return cls(airport_city=airport_city, airport_name=airport_name, airport_code=airport_code)

	def __str__(self):
		return "%s     (%s)" % (self.airport_city, self.airport_code)

class Flight(models.Model):
    origin_city = models.ForeignKey(Airport, related_name="origin_city", on_delete=models.CASCADE)
    dest_city = models.ForeignKey(Airport, related_name="dest_city", on_delete=models.CASCADE)
    airline_name = models.CharField(max_length=200)
    dept_datetime = models.DateTimeField('depature datetime')
    arr_datetime = models.DateTimeField('arrival datetime') 

    @classmethod
    def create(cls, origin_city, dest_city, airline, dept_date, arr_date):
        return cls(origin_city=origin_city, dest_city=dest_city, airline_name=airline,
                    dept_datetime=dept_date, arr_datetime=arr_date)

    def __str__(self):
        return "From: %s To: %s Airline: %s Dept: %s Arr: %s" % \
                                                        (self.origin_city.airport_city,
                                                        self.dest_city.airport_city, 
                                                        self.airline_name,
                                                        str(self.dept_datetime),
                                                        str(self.arr_datetime))

class Passenger(models.Model):
    sexField = models.CharField(max_length=200, null=True)
    first_name = models.CharField(max_length=200, null=True)
    second_name = models.CharField(max_length=200, null=True)
    birthDate = models.DateField(null=True)
    citizenship = models.CharField(max_length=200, null=True)
    documentNum = models.CharField(max_length=200, null=True)
    validTo = models.DateField(null=True)
    idNum = models.CharField(max_length=200, null=True)
    phone_country = models.CharField(max_length=200, null=True)
    phone_number = models.CharField(max_length=200, null=True)
    email = models.EmailField(primary_key=True)
    flights = models.ManyToManyField(Flight)

    def __str__(self):
        return "First_name: %s Email:%s" % (self.first_name, self.email)


class ReservationInfo(models.Model):
    PAYMENT = [
        (0, ""),
        (1, "Да"),
    ]

    is_paid = models.IntegerField(default=0, verbose_name=u'Оплата', choices=PAYMENT)
    tickets_num = models.PositiveSmallIntegerField(default=0, verbose_name=u'Билеты')
    tickets_txt = models.CharField(max_length=255, default='', verbose_name=u'Номера билетов', blank=True)
    status = models.CharField(max_length=15, verbose_name=u'Статус', default='BOOKED', blank=True)
    payment_method = models.CharField(max_length=50, verbose_name=u'Метод оплаты', default='', blank=True, null=True)
    payment_id = models.CharField(max_length=50, default='', blank=True, verbose_name=u'ID оплаты')
    provider_code = models.CharField(max_length=20, verbose_name=u'Код брони', default='', db_index=True)
    created = models.DateTimeField(
            default=timezone.now,
            verbose_name=u'Дата создания',
            db_index=True
        )

search/forms.py
from django import forms

from django.forms import CharField
import datetime
import re

from datetimewidget.widgets import DateWidget
from django_countries import countries

from .models import Airport

class FlightForm(forms.Form):
    origin_city = forms.CharField()
    dest_city = forms.CharField()
    date = forms.DateField(label="", widget=DateWidget(attrs={'required': True}, 
                                                        usel10n=True, bootstrap_version=3))

class BookingForm(forms.Form):
    CHOICES=[('M','M'),
            ('F','F')]
    sexField = forms.ChoiceField(label="", choices=CHOICES, widget=forms.RadioSelect())
    first_name = forms.CharField(label="First name", \
                                widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    second_name = forms.CharField(label="Second name", 
                                widget=forms.TextInput(attrs={'placeholder': 'Second name'}))
    birthDate = forms.DateField(label="Birth date", input_formats=('%d-%m-%Y',))
    
    citizenship = forms.ChoiceField(choices = list(countries))

    documentNum = forms.CharField(label="Document number")
    validTo = forms.DateField(label="Valid to", input_formats=('%d-%m-%Y',))
    idNum = forms.CharField(label="ID")
    
    phone_country = forms.CharField(label="Phone number")
    phone_number = forms.CharField(label="", min_length=10)
    email = forms.EmailField()

    def clean_phone_number(self):
        phone = self.cleaned_data['phone_number']

        if not re.match("\([0-9]{3}\)[0-9]{3}-[0-9]{2}-[0-9]{2}", phone):
            raise forms.ValidationError("Incorrect phone number format")

        return phone

search/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.utils import timezone
from django.http import JsonResponse
    

from datetime import datetime

from .models import Airport, Flight, Passenger
from .forms import FlightForm, BookingForm



def index(request):
    form = FlightForm(initial={'date': timezone.now()})

    return render(request, 'search/index.html', {'form': form})

def get_cities(request):
    data = {
        'cities': [x.airport_city for x in Airport.objects.all()]
    }
    return JsonResponse(data)

def check_cities(request):
    data = request.GET
    
    try:
        Airport.objects.get(airport_city=data['origin'])
        try:
            Airport.objects.get(airport_city=data['dest'])  
            response = {'valid': True}
        except Airport.DoesNotExist: 
            response = {'notValid': "There is no flights to this city"}
    except Airport.DoesNotExist:
        response = {'notValid': "There is no flights from this city"}
    
    return JsonResponse(response)


def search(request):
    data = request.POST

    try:
        date = datetime.strptime(data["date"], "%Y-%m-%d")
        origin_city = Airport.objects.get(airport_city=data["origin_city"])
        dest_city = Airport.objects.get(airport_city=data["dest_city"])
    except:
        error = "Error getting the airports"
        content = {
            'error': error
        }
    else:
        content = {
            'from': origin_city.airport_city,
            'to': dest_city.airport_city,
            'when': (date.date()),   
            'filter': Flight.objects.filter(
                origin_city__airport_code=origin_city.airport_code,
                dest_city__airport_code=dest_city.airport_code,
                dept_datetime__date=date
            ),  
        }
        
    return render(request, 'search/results.html', content)

def registerUser(data, flight_id):
    passenger = Passenger(sexField=data['sexField'],
                        first_name=data['first_name'],
                        second_name=data['second_name'],
                        birthDate=datetime.strptime(data["birthDate"], "%d-%m-%Y"),        
                        citizenship=data['citizenship'],
                        documentNum=data['documentNum'],
                        validTo=datetime.strptime(data["validTo"], "%d-%m-%Y"),            
                        idNum=data['idNum'],
                        phone_country=data['phone_country'],
                        phone_number=data['phone_number'],
                        email=data['email'])
    try:
        Passenger.objects.get(email=passenger.email)
        message = "Passenger already exists."
    except:
        message = "New passenger created."
            
    try:
        f = Flight.objects.get(pk=flight_id)
        passenger.save()
        passenger.flights.add(f)
    except:
        message = "Error... Flight does not exist."
    
    return message


def booking(request, flight_id):

    if request.POST:
        form = BookingForm(request.POST)
        if form.is_valid(): 
            message = registerUser(request.POST, flight_id)
            error = None 
            if "Error" in message:
                error = message
            content = {
                'message': message,
                'error': error,
            }
            return render(request, 'search/return_page.html', content)
    else:
        form = BookingForm(initial={'citizenship': "KZ"})

    content = {
        'form': form,
    }
    
    return render(request, 'search/booking.html', content)

templates/search/base.html
{% load static %}

<html>
    <head>

        {% block css %}
        {% endblock %}

           <!-- Google fonts -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Slabo+27px">
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto">
        
        <!-- Static -->
        <link rel="stylesheet" type="text/css" href="{% static 'search/css/style.css' %}" />

        {% block post-css %}
        {% endblock %}



    </head>
    
    <body>
        <main>
            {% block content %}
            {% endblock %}

            {%block javascript %}
            {% endblock %}

        </main>
    </body>
</html>

templates/search/booking.html
{% extends 'search\base.html'%}
{% load static %}

{% block css %}
    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
{% endblock %}

{% block post-css %}
    <!-- Load static -->
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/booking_style.css'%}"/>
{% endblock %}


{% block content %}
    <div class="booking">
        <h1> Booking </h1>

        <form id = "booking_form" action="" method="post">
            {% csrf_token %}
            
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}

            {% for field in form %}
                    {{ field.label_tag }} {{ field }}
            {% endfor %}

            
            <center> 
                <button class="btn btn-success" id = "submit"> Book </button>
            </center>
        </form> 
    </div>
{% endblock %}

{% block javascript %}
    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <!-- Input mask -->
    <script src="{% static 'search/js/inputmask.js' %}"></script>
    <script src="{% static 'search/js/inputmask.date.extensions.js' %}"></script>
    <script src="{% static 'search/js/jquery.inputmask.js' %}"></script>

    <script>
        $("#id_birthDate").inputmask({"mask": "99-99-9999"});
        $("#id_validTo").inputmask({"mask": "99-99-9999"});
        $("#id_idNum").inputmask({regex: "[0-9]*"});
        $('#id_phone_country').inputmask({"mask": "+9[999]"});
        $('#id_phone_number').inputmask({"mask": "(999)999-99-99"});
    </script>
{% endblock%}

templates/search/index.html
{% extends 'search/base.html' %}


{% block css %}

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <!-- For datepicker-->
    {{ form.media }}

{% endblock%}


{%block content %}
    
    <h1>Welcome to Aviata!</h1>

    <form id="form" action="{% url 'search:results' %}" method="post">
        {% csrf_token %}
        {{form.as_table}}

        <button class="btn btn-success" id = "submit">Search</button>
    </form>
    
{% endblock %}


{% block javascript %}
    <!-- JQuery for autocomplete -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script>
      var valid = false;

      $("form").submit(function(e) { 
            if(valid)
                return true;
            
                $.ajax({
                    url: '/ajax/check_cities/',
                    data: {
                        'origin': $('#id_origin_city').val(),
                        'dest': $('#id_dest_city').val()
                    },
                    dataType: 'json',
                    success: function(data) {
                        if(data.notValid) 
                            alert(data.notValid);
                        
                        if(data.valid) {
                            valid = true;
                            $("button").click();
                        }
                    }
                });

            return false;
      });


      $( function() {
        $.ajax({
            url: '/ajax/get_cities/',  
            data: {

            },
            dataType: 'json',
            success: function(data){
                if(data.cities) {
                    $( "#id_origin_city" ).autocomplete({
                        source: data["cities"]
                    });

                    $( "#id_dest_city" ).autocomplete({
                        source: data["cities"]
                    });
                }
            }
        });
      } );
    </script>
{% endblock %}

templates/search/results.html
{% extends 'search/base.html' %}

{% block content %}

    {% if error %}
        <h2 class='results_error'> {{ error }} </h2>
    {% else %}

        <div class="results_head">
             <h2>{{ from }}  →  {{ to }}</h2>
             <h3> {{ when}} </h3>
        </div>

        {% if filter %}
            <h3> Flight Results</h3>
        
            {% for f in filter %}
                
                <div  class="item">
                    <a href="/booking/{{f.id}}">
                        <h3 id="airline">{{f.airline_name }} </h3>
                        <p id="date"> {{ f.dept_datetime }} - {{ f.arr_datetime}} </p>
                    </a>
                </div>
                
            {% endfor %}
        {% else %}
            <h2 class='results_error'> No results</h2>
        {% endif %}
    {% endif %}

{% endblock %}

templates/search/return_page.html
{% extends 'search/base.html '%}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/css/booking_style.css'%}"/>
{% endblock %}


{% block content %}
    
    <center>
        {% if not error %}
        <h1 class="return_success"> Successfully booked! </h1>
        {% endif %}
        <p> {{ message }} </p>
        <a class="return_link"href = "/"> Return to the main page</a>
    </center>    
{% endblock %}